### ISSUE TITLE
Need access to salik and fines

### ISSUE THREAD

**Issue by wqrulhaq** [NotNalin/rtadubai#3]
Hi,
 Can you guide me if this api still works, I am making a fleet management system but need to integrate RTA apis, can guide me is this possible?
 
 I am trying to contact RTA without any success and api key is not available online I am stuck I need help. I can pay for the help if you know how can i get api access to RTA.
 
 Thanks

**Comment by NotNalin** [comment]
Hey @wqrulhaq,
This module works by web scraping rta.ae and salik.ae websites and is not really an API or uses any of RTA's API. As far as I know, neither RTA nor Salik has any API available for public use.

I originally created this as a hobby project back in 2022. However, I haven't maintained it since I no longer reside in the UAE. Both the rta.ae and salik.ae websites have since been updated, causing this module to break.

From what I know, the RTA part of this module still works when you install the development version. Unfortunately, the salik.ae website now uses Cloudflare, which makes web scraping nearly impossible and blocks requests from outside the UAE.

You can check the examples folder to see the code.

**Comment by wqrulhaq** [comment]
Thanks a lot for your reply, I will try to contact RTA when I reach dubai over emails they dont respond at all. i tried your code it does work though nice job thanks for that.
